name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "acf1e51a-04e7-4cb6-b971-ab1b57d33923" \
            --password "a3h8Q~KVRVxp5jCQ89MHNP6Ts6iOqm8dgak3Schr" \
            --tenant "4c5453b6-44f0-4067-9402-8352335e534b"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "36e65491-c697-416f-89f2-271ec338f7dc"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "acf1e51a-04e7-4cb6-b971-ab1b57d33923" \
            --password "a3h8Q~KVRVxp5jCQ89MHNP6Ts6iOqm8dgak3Schr" \
            --tenant "4c5453b6-44f0-4067-9402-8352335e534b"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "36e65491-c697-416f-89f2-271ec338f7dc"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan